version: "3.9"
services:
  venom-0:
    platform: linux/amd64
    image: miklosbagi/ovh-venom:${VENOM_VER}
    env_file:
      - .venom-env
    volumes:
      - ./tests/venom-0:/workdir/tests
      - ./results/venom-0:/workdir/results
    depends_on:
      postgres:
        condition: service_healthy

  venom-1:
    platform: linux/amd64
    image: miklosbagi/ovh-venom:${VENOM_VER}
    env_file:
      - .venom-env
    volumes:
      - ./tests/venom-1:/workdir/tests
      - ./results/venom-1:/workdir/results
    depends_on:
      # can run in parallel with venom-0
      postgres:
        condition: service_healthy

  venom-2:
    platform: linux/amd64
    image: miklosbagi/ovh-venom:${VENOM_VER}
    env_file:
      - .venom-env
    volumes:
      - ./tests/venom-2:/workdir/tests
      - ./results/venom-2:/workdir/results
    depends_on:
      # after venom-1
      venom-1:
        condition: service_completed_successfully
